python: 2.7

install:
  - pip install -r requirements.txt

before_script:
  - echo "Before script..."
  - which nosetests

script:
  - adb shell service call phone 2 s16 "10086"

after_script:
  - echo "after_script"
